export const data = {
  "en": {
    "intro_title": "You want to send <span class='text-amber-300 font-extrabold'>$1,000</span>.",
    "intro_sub": "Let's follow the journey of your money: how traditional banking works vs. why the <span class='text-[#14F195] font-bold'>Solana</span> network was created.",
    "btn_send": "Send $1,000 →",
    "bank_simple_title": "The money moves through a <span class='text-cyan-400'>system</span>.",
    "bank_simple_sub": "It travels between multiple institutions, hand by hand, before ever reaching the receiver.",
    "bank_check_title": "The bank <span class='text-amber-400'>checks</span> the payment.",
    "bank_check_sub": "Like a security checkpoint: verifying account balance, identity, limits, and permissions.",
    "bank_inst_title": "Another financial intermediary",
    "bank_inst_sub": "Your money passes through intermediary payment networks. Think of them as toll booths along the road.",
    "bank_fee_title": "A <span class='text-red-400'>fee</span> is deducted.",
    "bank_fee_sub": "Each middleman takes their cut. Your $1,000 shrinks down as services take processing fees.",
    "bank_wait_title": "<span class='text-red-400'>Waiting for clearance…</span>",
    "bank_wait_sub": "The transfer pauses for manual checks and banking hours. Like waiting in a long line at a physical office.",
    "bank_human_title": "Schedules and human delays",
    "bank_human_sub": "Financial organizations have weekends, closing hours, and queues that slow down execution.",
    "bank_received_title": "<span class='text-[#14F195]'>Finally Received.</span>",
    "bank_received_sub": "The funds arrived — but look at how slow, costly, and complex the path was.",
    "hook_title": "Skip the banks →<span class='text-cyan-400'>instant & direct</span>?",
    "hook_sub": "Same goal. Completely modern architecture with zero middlemen.",
    "btn_see_other": "See the other path →",
    "bc_title": "Imagine a <span class='text-cyan-400'>shared digital notebook</span>.",
    "bc_sub": "Every computer has an identical copy of this record book. When you send money, the record appears on all of them at once. No one can erase or falsify it. This is a <span class='text-cyan-400 font-bold'>blockchain</span>.",
    "solana_title": "<span class='text-[#14F195]'>WHO REPLACES THE BANK?</span>",
    "solana_sub": "Instead of one bank with managers, thousands of independent computers worldwide (validators) work together to verify every action honestly and openly.",
    "sol_speed_title": "<span class='text-[#14F195]'>DIRECT INSTANT TRANSFER</span>",
    "sol_speed_sub": "Value travels directly from sender to receiver. Computers confirm the transaction in milliseconds — no bank lines, no closing hours, no waiting.",
    "sol_fee_title": "<span class='text-[#14F195]'>MICRO-FEES: ZERO MIDDLEMAN CUTS</span>",
    "sol_fee_sub": "Network fees cost a tiny fraction of a single cent ($0.00025). The recipient gets the full $1,000 with zero hidden middleman fees.",
    "sc_title": "<span class='text-purple-400'>SMART CONTRACTS: AUTOMATED RULES</span>",
    "sc_sub": "Digital rules written in code: 'If condition is met, release money'. Executes automatically and honestly without lawyers, paperwork, or delays.",
    "defi_title": "<span class='text-blue-400'>DEFI: FINANCE WITHOUT BANKS</span>",
    "defi_sub": "People lend, save, and swap money directly with each other worldwide. All returns go directly to users, not bank headquarters.",
    "nft_title": "<span class='text-amber-400'>NFT: TRUE DIGITAL OWNERSHIP</span>",
    "nft_sub": "Mathematical proof that you are the sole genuine owner of a unique digital ticket, item, or document. Impossible to fake or duplicate.",
    "why_exist_title": "Why does <span class='text-[#14F195]'>Solana</span> exist?",
    "why_exist_sub": "To replace outdated, costly middlemen with a fast, affordable, and honest global network for direct value exchange.",
    "final_title": "What is Solana in simple words?",
    "final_sub": "It's an <span class='text-[#14F195] font-bold'>open global network</span> where computers worldwide work together to run instant transfers and apps directly between people — with zero middlemen.",
    "btn_next": "Next →",
    "btn_replay": "Replay Experience"
  },
  "ua": {
    "intro_title": "Ви хочете надіслати <span class='text-amber-300 font-extrabold'>$1,000</span>.",
    "intro_sub": "Простежимо шлях ваших грошей: від заплутаних банківських лабіринтів до того, як працює мережа <span class='text-[#14F195] font-bold'>Solana</span>.",
    "btn_send": "Надіслати $1,000 →",
    "bank_simple_title": "Гроші рухаються через <span class='text-cyan-400'>систему</span>.",
    "bank_simple_sub": "Вони переходять з рук в руки між установами, перш ніж досягнуть кінцевого отримувача.",
    "bank_check_title": "Банк <span class='text-amber-400'>перевіряє</span> платіж.",
    "bank_check_sub": "Як на митниці: звіряються баланси, ліміти, дозволи та підтвердження особи.",
    "bank_inst_title": "Інша фінансова установа",
    "bank_inst_sub": "Ваші гроші передаються посередникам. Уявіть їх як додаткові платні пункти пропуску на дорозі.",
    "bank_fee_title": "Знімається <span class='text-red-400'>комісія</span>.",
    "bank_fee_sub": "Кожен посередник бере свій відсоток. Від вашої тисячі доларів віднімається плата за обробку.",
    "bank_wait_title": "<span class='text-red-400'>Очікування підтвердження…</span>",
    "bank_wait_sub": "Процеси зупиняються через розклади банків. Ніби ви стоїте в довгій черзі до каси.",
    "bank_human_title": "Розклади та затримки",
    "bank_human_sub": "Організації мають вихідні дні, святкові розклади та ручні перевірки, які гальмують рух.",
    "bank_received_title": "<span class='text-[#14F195]'>Нарешті отримано.</span>",
    "bank_received_sub": "Гроші дійшли — але погляньте, наскільки повільним, дорогим та складним був цей шлях.",
    "hook_title": "Що, якби шлях був <span class='text-cyan-400'>миттєвим і прямим</span>?",
    "hook_sub": "Та сама мета. Але сучасна технологічна архітектура без посередників.",
    "btn_see_other": "Побачити інший шлях →",
    "bc_title": "Уявіть <span class='text-cyan-400'>спільну цифрову книгу записів</span>.",
    "bc_sub": "Кожен комп'ютер у світі має точну копію цієї книги. Коли ви робите переказ — запис з'являється у всіх одночасно. Його неможливо підробити чи стерти. Це і є <span class='text-cyan-400 font-bold'>блокчейн</span>.",
    "solana_title": "<span class='text-[#14F195]'>ХТО ТУТ ЗАМІСТЬ БАНКУ?</span>",
    "solana_sub": "Замість одного банку з директорами — тисячі незалежних комп'ютерів по всьому світу (валідаторів). Вони разом безперервно перевіряють чесність кожної дії.",
    "sol_speed_title": "<span class='text-[#14F195]'>ПРЯМИЙ ПЕРЕКАЗ БЕЗ ЗАТРИМОК</span>",
    "sol_speed_sub": "Гроші летять напряму від вас до отримувача. Комп'ютери підтверджують платіж миттєво — без черг, закритих відділень чи очікувань.",
    "sol_fee_title": "<span class='text-[#14F195]'>МІКРО-КОМІСІЯ БЕЗ ПОСЕРЕДНИКІВ</span>",
    "sol_fee_sub": "Комісія за переказ — крихітна частка цента ($0.00025). Отримувач одержує рівно $1,000 без прихованих зборів та банківських відсотків.",
    "sc_title": "<span class='text-purple-400'>СМАРТ-КОНТРАКТИ: АВТОМАТИЧНІ ПРАВИЛА</span>",
    "sc_sub": "Цифровий договір у коді: 'Якщо умову виконано — виплатити кошти'. Працює сам собою, чесно, без судів, нотаріусів чи людського фактора.",
    "defi_title": "<span class='text-blue-400'>DEFI: ФІНАНСИ БЕЗ БАНКІВ</span>",
    "defi_sub": "Обмін, кредити та збереження коштів безпосередньо між людьми. Всі відсотки отримують звичайні користувачі, а не банківські корпорації.",
    "nft_title": "<span class='text-amber-400'>NFT: ЦИФРОВИЙ СЕРТИФІКАТ ВЛАСНОСТІ</span>",
    "nft_sub": "Математичний доказ, що саме ви володієте унікальним квитком, цифровим артом чи документом. Його неможливо скопіювати чи підробити.",
    "why_exist_title": "Для чого взагалі створено <span class='text-[#14F195]'>Solana</span>?",
    "why_exist_sub": "Щоб замінити застарілу систему повільних посередників швидким, дешевим та чесним обміном грошима та цінностями для всього світу.",
    "final_title": "Отже, що таке Solana простими словами?",
    "final_sub": "Це <span class='text-[#14F195] font-bold'>глобальна публічна мережа</span>, де тисячі комп'ютерів разом забезпечують миттєві перекази та програми напряму між людьми — без посередників і банківських черг.",
    "btn_next": "Далі →",
    "btn_replay": "Спробувати ще раз"
  }
};
